### ISSUE TITLE
add references for PF morphology methods

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#100]
Hey @wrightaprilm,

What references do you think we need for the PF2 morphology methods and models. 

E.g. if someone runs kmeans on morphology with PF2, right now I ask them to cite:

PF2
RAxML
Paul's k-means paper

But should we also cite things for the models themselves (e.g. whatever the MK paper is, and whatever the paper is for the lewis correction). 

In molecular phylogenetics, we don't usually bother to cite the papers for all the individual models. This is for convenience rather than anything else. Especially in model selection - you'd be looking at 10s of citations for every paper that did model selection. But in morphology, it strikes me that most analyses will use a single model, so one or two extra references wouldn't be out of the question.

R

**Comment by wrightaprilm** [comment]
Lewis model + correction are here:

http://sysbio.oxfordjournals.org/content/50/6/913.short

It's the only thing that would need to be cited.

**Comment by roblanf** [comment]
Done: https://github.com/brettc/partitionfinder/commit/3445d971741224c7f66b5a6449a05400642c6eb3
