### ISSUE TITLE
Input and output

### ISSUE THREAD

**Issue by har-wradim** [brettc/partitionfinder#111]
I must say that the way input and output files/folders are treated is very inconvenient and risky:

* the program expects only two input files from the user: why force him to put them in one directory containing only them?
* the program silently overwrites log.txt if it existed and puts all its output into a subfolder with a predefined name. What if my own log.txt already contained something useful? What if I already had a subfolder called analysis?

The straight way of doing things in my opinion is something like:

    PartitionFinder --cfg my.cfg --phy my.phy --output-dir my-output 2> my.log

Related: #34

**Comment by har-wradim** [comment]
A minor addition: the manual incorrectly states that `InputFoldername` must be provided as a full path.

**Comment by roblanf** [comment]
These decisions are just part of making PartitionFinder simple for non-computational people to use. FOr what it's worth, the logfile is appended to not overwritten.

**Comment by har-wradim** [comment]
What's wrong in implementing the suggestions as optional parameters with their default values as they are currently?
