### ISSUE TITLE
Script execution

### ISSUE THREAD

**Issue by har-wradim** [brettc/partitionfinder#112]
* It would be great to have a list of python modules dependencies with respective version numbers  somewhere in the manual. Anaconda is arguably a rather messy thing.

* The PartitionFinder scripts also lack shebangs and moreover only from the manual can one learn that it requires Python 2.7 (the recommended shebang in this case is `#!/usr/bin/env python2.7`).

* Instructions on system-wide installation would be highly valuable for many users I guess. Something like:

        sudo mv partitionfinder-master /opt/partitionfinder
        # assume the shebang is there and the scripts are executable (chmod +x)
        sudo ln -s /opt/partitionfinder/PartitionFinder.py /usr/local/bin/PartitionFinder

**Comment by har-wradim** [comment]
Related: #75

**Comment by brettc** [comment]
Making PF conform to many of these ideals is certainly something we'd like to have time to do; having it install using `pip` would be great. I hope to work on some of this slowly.

I'm sure you have reasons for thinking Anaconda is "messy", but it is truly awesome if you're trying to support users with little command-line knowledge across multiple platforms. I think over half our downloads are from Windows users. (Which tells you why your instructions are of limited use).

**Comment by har-wradim** [comment]
Yes I see your point [although it is rather surprising that PF is so popular among Windows users], but those little changes would not harm: add the list of dependencies to the manual ("Either you install Anaconda and be happy or figure out how to install the following stuff: ...") and put the shebangs and make the scripts executable.

**Comment by brettc** [comment]
Yes, I hope to find some time to making these kinds of changes.

**Comment by roblanf** [comment]
I've added a list of dependencies in the manual, and a little dependency checker. I put shebangs in the main analysis scripts.
