### ISSUE TITLE
partitionfinder error on WIN7 32 bit

### ISSUE THREAD

**Issue by dongzhang0725** [brettc/partitionfinder#129]
I encountered an error when running partitionfinder2 in Win7 32bit, below is the screenshot of error information. By the way, it is normal on win10 64bit.
![sotq x60fbo 4of3bvtdl0q](https://user-images.githubusercontent.com/15956921/50322826-dead6800-0511-11e9-9ff4-5e5ae70040b2.png)

**Comment by roblanf** [comment]
It looks like RaxML is not running on your system. Please look at the instructions in the README.md file of the /programs folder, which gives you a link to download the right RAxML source code and then compile it on your machine.

**Comment by dongzhang0725** [comment]
Ok, I will try, thank you very much. Happy new year!
