### ISSUE TITLE
Forever issue python 2.7 vs 3; missing tables in one and in "3.*" it just make even more issues

### ISSUE THREAD

**Issue by StanleeKol** [brettc/partitionfinder#139]
**$python2.7 PartitionFinder.py MyrsPart/**
ERROR 
**Could not find the dependency tables**, please check that you have followed the installation instructions in the manual  and try again.

**$pip2 install tables**
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting tables
  Using cached tables-3.5.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.3 MB)
Collecting numexpr>=2.6.2
  Using cached numexpr-2.8.1.tar.gz (94 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/fj/3rr110l52cs7ctvhzy_ggvpw0000gn/T/pip-build-env-VCwMMv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel oldest-supported-numpy
       cwd: None
  Complete output (7 lines):
  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
  Collecting setuptools
    Using cached setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  ERROR: Could not find a version that satisfies the requirement oldest-supported-numpy (from versions: none)
  ERROR: No matching distribution found for oldest-supported-numpy

ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/fj/3rr110l52cs7ctvhzy_ggvpw0000gn/T/pip-build-env-VCwMMv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel oldest-supported-numpy Check the logs for full command output.

Any recommendations?

**Comment by roblanf** [comment]
hi @stanleewild - as you've identified, PF2 is coming to the end of it's life.

Luckily, it is superceded by something much better - IQTREE2. Most of what PF2 does is already implemented in IQTREE2, we are just finalising a few details. But if you use `MFP+MERGE` at the commandline with IQ-TREE2, you'll e able to optimise partitioning schemes.

Details here: http://www.iqtree.org/doc/Advanced-Tutorial (scroll down to 'choosing the right partitioning scheme')

**Comment by StanleeKol** [comment]
Hi @roblanf 
Thank you very much for the clarification!
I have one more question - please, regarding IQTREE2 having better capability than PF2 itself, how could I generate partitioning scheme or "partition file". PF2 was giving me best_scheme file with these data. Otherwise I don't know how can I provide to IQTree partitions file (except codon positions, but that is something else).
Thanks a lot!

Stan

**Comment by roblanf** [comment]
It's all there in the tutorial I think...

The tutorial shows you how to start from scratch (i.e. with data blocks, the same as you would start in PF2). It also shows you how to define a partitioning scheme.

If anything doesn't make sense, best to use the iq-tree google group: 
https://groups.google.com/g/iqtree

**Comment by StanleeKol** [comment]
Thank you @roblanf for the reply.
Unfortunately, I was not able to find out from the manual this thing. There is always only "example.nex" mentioned which has already defined the partitions. I did not find any function where I could just specify codon positions (data blocks) and then to get partitions. I send this question also to IQTree group, but without the response.
