### ISSUE TITLE
re-instate .cfg tests

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#14]
At some point, @brettc removed these tests for development. They need to get put back in.

There are two types of test currently missing:

1. Comparison of old .cfg file and current one, if there are saved subsets. E.g. were subsets analysed with RAxML or PhyML, and did the data block definitions change;

2. Basic .cfg checks, e.g. that data blocks do not contain the same site > once.

Rob

**Comment by brettc** [comment]
Fixed in 2c95c0fe52f6b3d2ba37a4fa860912d0cafef5cb
