### ISSUE TITLE
Update RAxML version

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#20]
We need to update the version of raxml we use to version 8.x

As far as I remember, there are some things which used to work in RAxML, which no longer work. I will attempt to work on this as soon as possible, so I can contact Alexis and resolve any outstanding issues with the RAxML code that we might need to be fixed. 

Note that someone has been compiling windows versions of RAxML, so once we have a version of RAxML we can use, we might be able to ask that person to compile us a version too...

https://github.com/stamatak/standard-RAxML/tree/master/WindowsExecutables_v8.1.15

**Comment by wrightaprilm** [comment]
One issue on this: some of the morphology things needed for TIGER are bugged in RAxML before 8.1.8, which I think might break some things for the molecular partitioning. But the way to handle this might just be to include instructions for morphologists, since they need to specify one additional thing vis cmdline_extras anyway (new ascertainment corrections).

**Comment by roblanf** [comment]
Can you clarify what you mean by 'bugged'.

Specifically, what versions of RAxML can we use that will work with your
morphology stuff?

Also, if there are things we *always* have to include for all morphology
analyses, we can code this in and save users the trouble.

On 18 January 2015 at 14:24, April Wright <notifications@github.com> wrote:

> One issue on this: some of the morphology things needed for TIGER are
> bugged in RAxML before 8.1.8, which I think might break some things for the
> molecular partitioning. But the way to handle this might just be to include
> instructions for morphologists, since they need to specify one additional
> thing vis cmdline_extras anyway (new ascertainment corrections).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/20#issuecomment-70395021>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by wrightaprilm** [comment]
Yes: The ascertainment bias corrections for SNPs and morphology implemented were failing some test in the RAxML package. Anything after 8.1.8 works for morphology. It would be a pretty serious rarity for morph people not to need a correction of the type.

RAxML google group thread here:
https://groups.google.com/forum/#!topic/raxml/9CLyKbC1n2E

**Comment by roblanf** [comment]
This is now done. The versions are different, but not by much: 

Mac: 8.1.16 (https://github.com/roblanf/standard-RAxML)
Windows: 8.1.15 (https://github.com/roblanf/standard-RAxML/tree/master/WindowsExecutables_v8.1.15)

They appear to work just fine as drop in replacements for the older versions, which is great
