### ISSUE TITLE
Add support for additional RAxML models

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#23]
RAxML 8.x has a lot more models available. Easy to add support for these.

**Comment by roblanf** [comment]
Note this from the latest RAxML manual too:

"By appending X to the model strings you indicate that you want to use a maximum likelihood estimate for the base frequencies"

We could easily add this, e.g. 

GTR, GTRX, GTR+G, GTRX+G, etc.

We could use the same notation for PhyML models too, which have the same options (except you specify the models through the commandline)

**Comment by cmayer** [comment]
Hi,

I do not understand this. The GTR model does include estimates for base frequencies inherently.
How could this be switched on or of.
Its a bit like B&B (Bed and Breakfast) with or without a bed.

Best
Christoph


Am 18.01.2015 um 03:46 schrieb roblanf:

> Note this from the latest RAxML manual too:
> 
> "By appending X to the model strings you indicate that you want to use a maximum likelihood estimate for the base frequencies"
> 
> We could easily add this, e.g.
> 
> GTR, GTRX, GTR+G, GTRX+G, etc.
> 
> We could use the same notation for PhyML models too, which have the same options (except you specify the models through the commandline)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
The difference is that they can be estimated empirically (just add up all
the bases in the alignment) or via ML. If they are estimated via ML that
costs you 4 extra parameters. Usually empirical estimates are fine.



On 19 January 2015 at 04:14, cmayer <notifications@github.com> wrote:

> Hi,
>
> I do not understand this. The GTR model does include estimates for base
> frequencies inherently.
> How could this be switched on or of.
> Its a bit like B&B (Bed and Breakfast) with or without a bed.
>
> Best
> Christoph
>
>
> Am 18.01.2015 um 03:46 schrieb roblanf:
>
> > Note this from the latest RAxML manual too:
> >
> > "By appending X to the model strings you indicate that you want to use a
> maximum likelihood estimate for the base frequencies"
> >
> > We could easily add this, e.g.
> >
> > GTR, GTRX, GTR+G, GTRX+G, etc.
> >
> > We could use the same notation for PhyML models too, which have the same
> options (except you specify the models through the commandline)
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> ****************************************
> Dr. Christoph Mayer
> Email: c.mayer.zfmk@uni-bonn.de
> Tel.: +49 (0)228 9122 403
>
> Zoologisches Forschungsmuseum Alexander Koenig
> - Leibniz Institut für Biodiversität der Tiere -
> Adenauerallee 160
> 53113 Bonn, Germany
> www.zfmk.de
>
> Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
> Sitz: Bonn
> ****************************************
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/23#issuecomment-70416382>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
to clarify (and so I don't forget), ML base frequencies cost you 4 parameters, but only 3 free parameters, because they sum to 1.0

**Comment by roblanf** [comment]
Done. The default is to use empirical base frequencies, but all of the models are now in there. Including all the protein models, AND a GTR protein model.
