### ISSUE TITLE
Feature request: mrBayes block generation?

### ISSUE THREAD

**Issue by miltontan** [brettc/partitionfinder#24]
Would it be possible for PartitionFinder to automatically create mrBayes blocks for partitioned analyses? I feel like this could help automate using PartitionFinder for mrBayes analyses, rather than having to manually construct the bayes block.

**Comment by roblanf** [comment]
Nice idea. We can take a look at this. It would be great if you could paste a few examples of MrBayes blocks here. 

More specifically, we'd need to know:

1. How to link / unlink rates across partitions (note that this is the overall rate, not individual branchlengths)

2. Descriptions of all the models implemented in the latest version of MrBayes

3. How to specify and enforce blocks of sites for MrBayes

**Comment by wrightaprilm** [comment]
I might take a crack at the simple partition definition (i.e. not the full model block), which can be catted with the matrix and block pretty easily. I need to make some changes to how the RAXML partitions are put out for morphology, anyhoo.

**Comment by miltontan** [comment]
I am not sure about the answer to all of those, but the wiki here for mrBayes I think lists out most of what you're asking for: http://mrbayes.sourceforge.net/wiki/index.php/Evolutionary_Models_Implemented_in_MrBayes_3

Specifically, they discuss partitioning here: http://mrbayes.sourceforge.net/wiki/index.php/Evolutionary_Models_Implemented_in_MrBayes_3#Partitioned_Models

I often use this guide for setting models: https://gist.github.com/brantfaircloth/895282

**Comment by roblanf** [comment]
Hi All, 

This is now done in PF2. Check the releases page.

Rob
