### ISSUE TITLE
Add support for sequential analyses over a model list

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#25]
One thing about raxml is that you can only use a single model of rate variation for each partition (parameters estimated independently per partition). 

So one thing that would be useful in PF would be to be able to provide a list of models, e.g. 

models = GTR, GTR+G, GTR+I+G; 

and then rather than consider combinations of these models, just run three analyses - one with all models set to GTR, one with all set to GTR+G, and one with GTR+I+G. 

We would then just pick the scheme with the lowest AICc, as usual, and output that along with the best models. 

This is a low priority, as it is fairly cosmetic, but user-friendly nonetheless

**Comment by cmayer** [comment]
Hi Rob,

that feature would allow users to use PF also as a normal model test program.
Why not.
But it should not be the default.

Best
Christoph


Am 18.01.2015 um 03:44 schrieb roblanf:

> One thing about raxml is that you can only use a single model of rate variation for each partition (parameters estimated independently per partition).
> 
> So one thing that would be useful in PF would be to be able to provide a list of models, e.g.
> 
> models = GTR, GTR+G, GTR+I+G;
> 
> and then rather than consider combinations of these models, just run three analyses - one with all models set to GTR, one with all set to GTR+G, and one with GTR+I+G.
> 
> We would then just pick the scheme with the lowest AICc, as usual, and output that along with the best models.
> 
> This is a low priority, as it is fairly cosmetic, but user-friendly nonetheless
> 
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
Not done.
