### ISSUE TITLE
Test morphology partitionfinder

### ISSUE THREAD

**Issue by wrightaprilm** [brettc/partitionfinder#27]
Hi all-

If anyone wants to give a spin to the morphological extension to PF, it's here:

https://github.com/wrightaprilm/partitionfinder/tree/feature/morphology2

instructions are in the README. It was mostly playtested on 335 datasets on Ubuntu, though I think @pbfrandsen got it working on Mac. Feel free to reply here with issues, or raise them on the morphology2 branch on my fork.

**Comment by roblanf** [comment]
done.
