### ISSUE TITLE
Keep (some) phylofiles

### ISSUE THREAD

**Issue by maxmaronna** [brettc/partitionfinder#30]
It woud be useful to keep some files, like the best "Subset Partitions", or even all of the tested partitions.

**Comment by roblanf** [comment]
This is a great idea.

We could do this by a single pass of the best subset at the end, calling
the function to write summary files of the subsets. We could also then name
them by their ID in the best subset, (e.g. best_subset_1.txt etc), rather
than by the long hex names.

On 27 January 2015 at 16:29, maxmaronna <notifications@github.com> wrote:

> It woud be useful to keep some files, like the best "Subset Partitions",
> or even all of the tested partitions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/30>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
This is now implemented. I just forgot to mention it.
