### ISSUE TITLE
building phyml from source

### ISSUE THREAD

**Issue by biologyguy** [brettc/partitionfinder#39]
There are a bunch of sim links in `partitionfinder/programs/phyml_source/`, and `./configure` doesn't run:

    $: ./configure
    configure: error: cannot find install-sh or install.sh in "." "./.." "./../.."

Am I missing something?
Thanks,
-Steve

**Comment by roblanf** [comment]
Hi Steve,

If you're on Mac/Windows, you should just be able to use the packaged binaries. If you're compiling for Linux, you should be able to run this:

./waf configure build

Rob

**Comment by biologyguy** [comment]
Thanks for getting back to me Rob,
I'm trying to build on a Linux cluster, and unfortunately your recommended fix didn't pan out. I dumped the output to a Gist at https://gist.github.com/biologyguy/7609b798f1611aaef2e1
Any other suggestions?
Thanks again,
-Steve

**Comment by roblanf** [comment]
Hi Steve,

Sorry - we're out of ideas here. Unfortunately we can't (for obvious
reasons) do a very good job of supporting other folks software (i.e. PhyML
in this case) on other platforms. The best I can suggest, which is probably
not very satisfactory I know, is to find a sysadmin for your cluster who
knows Linux well enough to figure it out. I know many others have managed
to get things going on linux, so it's certainly not impossible.

You could also try posting on the google group for help. Someone might
chime in.

Cheers,

Rob

On 23 February 2015 at 10:42, Steve Bond <notifications@github.com> wrote:

> Thanks for getting back to me Rob,
> I'm trying to build on a Linux cluster, and unfortunately your recommended
> fix didn't pan out. I dumped the output to a Gist at
> https://gist.github.com/biologyguy/7609b798f1611aaef2e1
> Any other suggestions?
> Thanks again,
> -Steve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/39#issuecomment-75472210>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by biologyguy** [comment]
Right-o, thanks for trying. I'll shoot you a note if I get it sorted out.
Take care,
-Steve

**Comment by biologyguy** [comment]
Hi Rob,
It took me a few hours, but as is so often the case the solution is fairly simple... The sym links in the source you have forked are all broken, so `autoconf` has to be called again to get everything back in line, but then a line is included in `configure` that is causing `make` to choke. Commenting out that line does the trick for me, and hopefully will for others as well. I've tested it on a few different distros, and all seems to be good. So, without further ado, below are the steps a Linux user can take to get partitionfinder up and running :)

    $: git clone https://github.com/brettc/partitionfinder.git
    $: cd partitionfinder/programs/
    $: rm BUILDING.txt format.latex phyml phyml.exe raxml raxml.exe
    $: cd phyml_source/
    $: autoreconf -fi
    $: perl -i -pe 's/ARCH_flag\=/#ARCH_flag=/' configure
    $: ./configure
    $: make
    $: mv src/phyml ../
    $: cd ../
    $: git clone https://github.com/brettc/standard-RAxML.git
    $: cd standard-RAxML
    $: make -f Makefile.<desired build>.gcc
    $: rm *.o
    $: mv  raxmlHPC-<desired build> ../raxml
 
I hope this will help out anyone else who is running into the same problems I did.
Take care,
-Steve

**Comment by roblanf** [comment]
Hi Steve,

Thanks, that's really awesome information to have. I'll put a link from the
FAQ for Linux compiling when I get a chance.

Cheers,

Rob

On 24 February 2015 at 08:40, Steve Bond <notifications@github.com> wrote:

> Hi Rob,
> It took me a few hours, but as is so often the case the solution is fairly
> simple... The sym links in the source you have forked are all broken, so
> autoconf has to be called again to get everything back in line, but then
> a line is included in configure that is causing make to choke. Commenting
> out that line does the trick for me, and hopefully will for others as well.
> I've tested it on a few different distros, and all seems to be good. So,
> without further ado, below are the steps a Linux user can take to get
> partitionfinder up and running :)
>
> $: git clone https://github.com/brettc/partitionfinder.git
> $: cd partitionfinder/programs/
> $: rm BUILDING.txt format.latex phyml phyml.exe raxml raxml.exe
> $: cd phyml_source/
> $: autoreconf -fi
> $: perl -i -pe 's/ARCH_flag\=/#ARCH_flag=/' configure
> $: ./configure
> $: make
> $: mv src/phyml ../
> $: cd ../
> $: git clone https://github.com/brettc/standard-RAxML.git
> $: cd standard-RAxML
> $: make -f Makefile.<desired build>.gcc
> $: rm *.o
> $: mv  raxmlHPC-<desired build> ../raxml
>
> I hope this will help out anyone else who is running into the same
> problems I did.
> Take care,
> -Steve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/39#issuecomment-75640498>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com
