### ISSUE TITLE
user schemes seem to be broken

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#42]
on develop branch. @brettc, can you take a quick look?

I can't seem to specify a user scheme, e.g. like this for the example dataset:

```

## SCHEMES, search: all | greedy | rcluster | hcluster | user | kmeans ##
[schemes]
search = greedy;

s1 = (Gene1_pos1) (Gene1_pos2) (Gene1_pos3) (Gene2_pos1) (Gene2_pos2) (Gene2_pos3) (Gene3_pos1) (Gene3_pos2) (Gene3_pos3);

```

**Comment by brettc** [comment]
It works here. What error are you getting? (Note that in the text above, you're still specifying "greedy".

**Comment by roblanf** [comment]
Well, there you go. It works here too (with greedy and user searches). Sorry for an (a) lame and (b) wrong bug report.
