### ISSUE TITLE
cython tiger implementation has a flag requiring OS 10.8 or higher

### ISSUE THREAD

**Issue by pbfrandsen** [brettc/partitionfinder#43]
The cython version of tiger on the development branch has a flag requiring mac os 10.8 or greater-`-mmacosx-version-min=10.8`. It would be nice if we could compile the cython code on a linux machine.

**Comment by brettc** [comment]
Unfortunately I don't have a linux test machine. Try commenting out the extra-compile-arg and seeing if it works. Once we know, it is simple to modify setup.py to detect the platform and add the right flags.

**Comment by roblanf** [comment]
since tiger is not supported in PF2, I'm going to leave this open but take if off the PF2 milestone.

**Comment by roblanf** [comment]
done - we don't use cython TIGER any more.
