### ISSUE TITLE
We still call fast_TIGER instead of the new cython tiger implementation for rate calculation

### ISSUE THREAD

**Issue by pbfrandsen** [brettc/partitionfinder#44]
We are still calling fast_TIGER within kmeans.py gen_per_site_stats(). I thought that we made the change to the cython tiger rates during the workshop, but I can't find that function anywhere.

**Comment by roblanf** [comment]
@brettc any clues on this?

**Comment by pbfrandsen** [comment]
I noticed this a couple of months ago. I'm sure that we switched things
over at our 'hackathon', but I wasn't able to find it in any of the
features or in the commit history.

I'm pretty sure that I remember the changes that we need to make to get it
to run. I can work on this at the end of this week.

**Comment by brettc** [comment]
Let me know if anything isn't clear. You should be able use numpy arrays
all the way through the analysis now.

**Comment by roblanf** [comment]
Do we know how we're going to deal with TIGGER yet? Are we releasing a separate binary in the /programs folder? Or are we asking users to compile it themselves. 

I have to say that if entropy is roughly as good in our tests, I think we should probably remove support for TIGGER. Keep it in, but as a private option that isn't mentioned anywhere. My fear is that many folks want to try everything to get the best model. And then they'll all get hung up compiling TIGGER, and hate us forever.

**Comment by brettc** [comment]
I agree that if entropy is better we should ditch tigger. But if we plan to
distribute something that works, we need to include phyml (or raxml) which
require compiling already. So we can just distribute the binary for tigger
too.

If I can get pyinstaller working, we might have a better solution...

**Comment by roblanf** [comment]
OK cool. I'll get onto running the entropy tests (i'll just compare them
with fast_TIGER, since it should be the same).

I'll post results here, and we can make a decision on which of three things
to do:

1. Remove TIGGER all together (simplest for us to maintain)
2. Include TIGGER but don't mention it to users (not sure I see the point
of this option, to be honest)
3. Include TIGGER and put it in the manual, and support users (probably
fine, but may also create extra work for supporting PF, and this would be
work that I probably couldn't do)



On 4 August 2015 at 09:18, Brett Calcott <notifications@github.com> wrote:

> I agree that if entropy is better we should ditch tigger. But if we plan to
> distribute something that works, we need to include phyml (or raxml) which
> require compiling already. So we can just distribute the binary for tigger
> too.
>
> If I can get pyinstaller working, we might have a better solution...
>
> On Tue, Aug 4, 2015 at 9:52 AM roblanf <notifications@github.com> wrote:
>
> > Do we know how we're going to deal with TIGGER yet? Are we releasing a
> > separate binary in the /programs folder? Or are we asking users to
> compile
> > it themselves.
> >
> > I have to say that if entropy is roughly as good in our tests, I think we
> > should probably remove support for TIGGER. Keep it in, but as a private
> > option that isn't mentioned anywhere. My fear is that many folks want to
> > try everything to get the best model. And then they'll all get hung up
> > compiling TIGGER, and hate us forever.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/brettc/partitionfinder/issues/44#issuecomment-127416301
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/44#issuecomment-127429530>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by brettc** [comment]
Note that FAST_tiger is actually pretty slow compared to tigger. But the
results should be the same (mostly -- we handle the unknown sites
differently I think).

We can always 'try' to import tigger, and the give a nice message if it
ain't there.

**Comment by roblanf** [comment]
so, here are the results so far. Entropy usually does better (often by a fair bit), and occasionally does a little worse than tiger. 

Unless the last few datasets throw up some drastic surprises, my vote is to move kmeans to work only with entropy.

Here are the AICc scores on the first few datasets

![rplot](https://cloud.githubusercontent.com/assets/895251/9055350/b414ed46-3acd-11e5-8805-462e06a17546.jpg)

One interesting thing that this figure doesn't show is that entropy kmeans is doing all of this while selecting drastically fewer subsets. This seems like a very good thing, given the tendency in simulation for tiger kmeans to oversplit. In fact, in every case, entropy kmeans gets FEWER subsets than the greedy algorithm. 

![rplot](https://cloud.githubusercontent.com/assets/895251/9055392/1f33b5b2-3ace-11e5-8348-5aa57f7adf85.jpg)

**Comment by roblanf** [comment]
sorry - in *many* cases we get fewer subsets than the greedy algorithm. But in every case we get a lot fewer than tigger.

**Comment by brettc** [comment]
The entropy calculation scales way better too, right? So definitely a
better option than tigger.

**Comment by pbfrandsen** [comment]
It is encouraging to see that fewer subsets are selected with entropies.
Entropies have a couple of other desirable characteristics as well:

1. They are O(n) to calculate as opposed to of O(n^2) for tiger rates.
2. They don't change as you split the subsets. One of the things that I
remain a bit uncomfortable about with the new algorithm is the iterative
splitting and 'optimizing' of AIC scores. With entropies, something like a
bisection search for the optimal number of k's would be totally reasonable.
We probably don't want to worry about that with this release, but it's
something that could be easily written up (I already have a crude version
in paul_develop) if we decided we wanted to.

There are a couple of reasons why I think it might be good to keep the
tiger rates in the background for the time being (or even just in a feature
branch): (1) I would like to experiment with using DBSCAN on the distance
matrix that we make with the cython implementation of tiger. I feel like
this would be the best way to actually cluster *similar* sites together,
rather than sites that are 'equally dissimilar'. DBSCAN is O(n^2), but I
think that is just because you have to make a distance matrix (which we
already do when we compare bit sets). The actual clustering should be
pretty fast. Also, since all rates are between 0 and 1, a reasonable
epsilon might not be terribly difficult to estimate (2) Even though we get
better AICc scores with entropies, I'm not entirely convinced that they
really should be better than the tiger rates since entropies are a bit more
of a crude measure. However, this one is debatable, since I'm not convinced
that tiger rates are giving what we want either...

**Comment by roblanf** [comment]
I'd be happy to keep them in the background or on a branch. @brettc, what's the best thing to do here? 

R

**Comment by brettc** [comment]
My guess: while our brains our in it, do the minimal work to make tigger
work (better off to use my code if possible, I think). Then make PF work
without it, but detect it if it is compiled. Make zero commitment to it
working in the release (ie. an "experimental feature"). I'd prefer that to
keep it on another branch.

Paul -- is there much work to make it happen now?

**Comment by roblanf** [comment]
Sounds good. I'll leave you guys to get it working, and I just won't
mention it anywhere in the documentation.

R

On 5 August 2015 at 07:53, Brett Calcott <notifications@github.com> wrote:

> My guess: while our brains our in it, do the minimal work to make tigger
> work (better off to use my code if possible, I think). Then make PF work
> without it, but detect it if it is compiled. Make zero commitment to it
> working in the release (ie. an "experimental feature"). I'd prefer that to
> keep it on another branch.
>
> Paul -- is there much work to make it happen now?
> On Wed, 5 Aug 2015 at 09:44 roblanf <notifications@github.com> wrote:
>
> > I'd be happy to keep them in the background or on a branch. @brettc
> > <https://github.com/brettc>, what's the best thing to do here?
> >
> > R
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/brettc/partitionfinder/issues/44#issuecomment-127771182
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/44#issuecomment-127772965>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by pbfrandsen** [comment]
This sounds good. It shouldn't be much work to get things working. I should
have time over the next couple of days.

sent from my mobile phone, apologies for any typos

**Comment by roblanf** [comment]
Final data. Entropy is great. 7/10 datasets it improves the AICc score. And the ones that get a worse AICc score don't get much worse. I.e. the average improvement is much bigger than the average worsening (is that a word?).

![rplot](https://cloud.githubusercontent.com/assets/895251/9077360/7d88e20c-3b70-11e5-8959-09872c1d1d31.jpg)

**Comment by roblanf** [comment]
@pbfrandsen, it would be neat to compare runtimes for the published fast_TIGER rates with entropy. I.e.,  do you think you can leave the fast_TIGER option in the code as well. 

My suggestion is that we don't even make an option to fast_TIGER or TIGGER on the commandline, but instead just leave it so that it has to be hard-coded. Do you think it's feasible to do this? If we can, then I could compare runtimes, and add that to the PF2 ms. 

R

**Comment by pbfrandsen** [comment]
Whoops, I didn't see this comment until now. I just removed the fast_TIGER stuff with the last commit, I'll add it back in...

**Comment by pbfrandsen** [comment]
Ok, fast_TIGER is back in. Option '--kmeans fast_tiger'. Entropies are run by default, '--kmeans tiger' will run the cython rates. We can remove the options and leave the code for later if we wish?

@brettc for some reason I have to do a really clunky thing with the cython tiger rates. Kmeans requires an 'array of arrays' with each observation in it's own array, i.e. [[rate_1][rate_2][rate_3]], which makes total sense if we were working with more than one dimension. However, the cython rates are output as a single dimensional array [rate_1 rate_2 rate_3]. I'm sure there is a nice numpy way to convert this, but right now, I make a new list (line 144 in kmeans.py), then convert it back to a numpy array (line 50 kmeans.py). I do a similar thing with entropies. I don't know that this takes that long in reality (and is certainly better than calling an external program and parsing the rates), but it is kind of clunky...

**Comment by roblanf** [comment]
Hey Paul,

This is cool. Can you include somewhere (maybe just in the /docs folder as
a separate text document) detailed instructions on where to get fast_TIGER
and TIGGER, and how to compile them. Try and make the instructions idiot
proof, and then I'll test them as a bona-fide idiot when I try and get both
programs running.

We can leave these instructions in the repo, but I'll remove them from the
download on my website, in an attempt to make it clear that we are not
promoting these methods.

R

On 7 August 2015 at 03:23, Paul Frandsen <notifications@github.com> wrote:

> Closed #44 <https://github.com/brettc/partitionfinder/issues/44>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/44#event-375546335>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by pbfrandsen** [comment]
Hi Rob,

Sure thing! I need to sort out compiling tigger on Linux and I don't have
access to a Windows machine, but I'll write up instructions for both Linux
and Mac.

Paul

**Comment by roblanf** [comment]
since we're not supporting it, you can just do it for whatever. For me, all
I need is mac for now.

R

On 7 August 2015 at 12:31, Paul Frandsen <notifications@github.com> wrote:

> Hi Rob,
>
> Sure thing! I need to sort out compiling tigger on Linux and I don't have
> access to a Windows machine, but I'll write up instructions for both Linux
> and Mac.
>
> Paul
>
> On Thu, Aug 6, 2015 at 5:40 PM, roblanf <notifications@github.com> wrote:
>
> > Hey Paul,
> >
> > This is cool. Can you include somewhere (maybe just in the /docs folder
> as
> > a separate text document) detailed instructions on where to get
> fast_TIGER
> > and TIGGER, and how to compile them. Try and make the instructions idiot
> > proof, and then I'll test them as a bona-fide idiot when I try and get
> both
> > programs running.
> >
> > We can leave these instructions in the repo, but I'll remove them from
> the
> > download on my website, in an attempt to make it clear that we are not
> > promoting these methods.
> >
> > R
> >
> > On 7 August 2015 at 03:23, Paul Frandsen <notifications@github.com>
> wrote:
> >
> > > Closed #44 <https://github.com/brettc/partitionfinder/issues/44>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/brettc/partitionfinder/issues/44#event-375546335>.
> > >
> >
> >
> >
> > --
> > Rob Lanfear
> > School of Biological Sciences,
> > Macquarie University,
> > Sydney
> >
> > phone: +61 (0)2 9850 8204
> >
> > www.robertlanfear.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/brettc/partitionfinder/issues/44#issuecomment-128517680
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/44#issuecomment-128565934>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com
