### ISSUE TITLE
checks on bad subsets are not working

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#45]
Hey @brettc, can you take a look at this ASAP? This is a very important check that currently doesn't work.

Previously, we have checked that sites in data blocks are non-overlapping, and also spit a warning for any missing sites. 

E.g. with the aminoacid example file:

This is fine
'''
[data_blocks]
COI     =   1-407;
COII    =   408-624;
EF1a    =   625-949;
'''

This should spit a warning about missing sites 1-3 and 941-949
'''
[data_blocks]
COI     =   4-407;
COII    =   408-624;
EF1a    =   625-940;
'''

And this should quit with an error about a site only being allowed to appear in a single data block:
'''
[data_blocks]
COI     =   1-407;
COII    =   408-624;
EF1a    =   625-949;
OOPS = 1-949;
'''

Right now, the second and third options are not behaving properly. No warning, and no error. Can we re-instate these?

**Comment by brettc** [comment]
Fixed on develop branch 49075e22b049c66cbd9c632b94aa0324fd611dbf with two new tests.
