### ISSUE TITLE
PhyML output filename conventions on linux

### ISSUE THREAD

**Issue by kgori** [brettc/partitionfinder#47]
Hi,

I ran into a problem running partition finder on linux. This applies to using it with phyml version 20141029, but maybe affects phyml on linux more generally. I'm running the test example "python PartitionFinderProtein.py examples/aminoacid".
On linux phyml output files don't have a .txt suffix - they just end .phy_phyml_tree (or stats). However, your file handling code in partfinder.phyml.py (functions make_tree_path and make_output_path) assumes that the .txt suffix is there. So this leads to an error when trying to read the BioNJ starting tree at the beginning of the analysis. The tree file gets written successfully, it just doesn't have the suffix, so PF can't find it, and it errors out with a standard python IOError.
If I alter the code in phyml.py (just delete ".txt" in the three places it occurs) then everything runs OK.

I don't know if you've run into this problem before, or if you already have another fix, but I thought I'd let you know.

**Comment by roblanf** [comment]
Thanks! We'll look into this and get it fixed.

Rob

On 8 July 2015 at 15:13, Kevin Gori <notifications@github.com> wrote:

> Hi,
>
> I ran into a problem running partition finder on linux. This applies to
> using it with phyml version 20141029, but maybe affects phyml on linux more
> generally. I'm running the test example "python PartitionFinderProtein.py
> examples/aminoacid".
> On linux phyml output files don't have a .txt suffix - they just end
> .phy_phyml_tree (or stats). However, your file handling code in
> partfinder.phyml.py (functions make_tree_path and make_output_path)
> assumes that the .txt suffix is there. So this leads to an error when
> trying to read the BioNJ starting tree at the beginning of the analysis.
> The tree file gets written successfully, it just doesn't have the suffix,
> so PF can't find it, and it errors out with a standard python IOError.
> If I alter the code in phyml.py (just delete ".txt" in the three places it
> occurs) then everything runs OK.
>
> I don't know if you've run into this problem before, or if you already
> have another fix, but I thought I'd let you know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/47>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by brettc** [comment]
This is fixed in db40c5d53ae87ec4fb6298ff0d17ffb092b19699
