### ISSUE TITLE
tigger matrix

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#49]
So I just realised something that could speed things up, but I don't think there's any point implementing it. 

At the start of a kmeans tigger run, we calculate the pairwise compatibility matrix for the WHOLE ALIGNMENT. THe site rates are then just colum averages, right? 

If that's right, then we never need to calculate anything with tigger again, because for any given subset, we should be able to extract the relevant bit of the matrix and just re-calculate the column averages. 

At the moment we re-run tigger for every single new subset.

Thoughts? Have I missed something?

I think this is only worth impelmenting if it turns out that entropies aren't so good after all. For that we need to do some benchmarking.

R

**Comment by brettc** [comment]
This is def. doable. Not sure how much it would speed things up though, as
the compatibility score calculation is what scales poorly. Wouldn't we
still need to do this?

**Comment by roblanf** [comment]
Nope. The point is this.

Right now we calculate compatibility matrices for the whole alignment in
step one, and then for every subsequent subset in all future steps. I.e.
during a run of k-means we might calculate compatibility ~50 times for each
site.

My point is that we only need to do the very first calculation. All other
calculations are just using subsets of the matrix of all compatibility
scores.

However, there are lots of reasons why this won't lead to a big speedup:

1. Most kmeans runs do not calculate the compatibility of a site anything
like 50 times. It might be more like 3 or 4 on average.

2. After the first step, the alignments get smaller and smaller. And since
the algorithm is N-squared, the smaller alignments are a lot lot quicker.

So, on balance, I suspect this potential improvement might speed us up by
less than twofold, and that ONLY on the TIGGER calculations. ~90% of the
algorithm (for the vast majority of cases) is spent doing things other than
TIGGER calculations. So even if we can double the speed of the way we use
TIGGER, we might get at best a ~5% speedup.

On that basis, I'll close this issue because it's a neat but entirely
useless idea.

On 30 July 2015 at 07:55, Brett Calcott <notifications@github.com> wrote:

> This is def. doable. Not sure how much it would speed things up though, as
> the compatibility score calculation is what scales poorly. Wouldn't we
> still need to do this?
> On Tue, 28 Jul 2015 at 16:43 roblanf <notifications@github.com> wrote:
>
> > So I just realised something that could speed things up, but I don't
> think
> > there's any point implementing it.
> >
> > At the start of a kmeans tigger run, we calculate the pairwise
> > compatibility matrix for the WHOLE ALIGNMENT. THe site rates are then
> just
> > colum averages, right?
> >
> > If that's right, then we never need to calculate anything with tigger
> > again, because for any given subset, we should be able to extract the
> > relevant bit of the matrix and just re-calculate the column averages.
> >
> > At the moment we re-run tigger for every single new subset.
> >
> > Thoughts? Have I missed something?
> >
> > I think this is only worth impelmenting if it turns out that entropies
> > aren't so good after all. For that we need to do some benchmarking.
> >
> > R
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/brettc/partitionfinder/issues/49>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/49#issuecomment-126108001>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com
