### ISSUE TITLE
fix parser tests

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#50]
A bunch of failing tests for the parser. I've looked, but can't figure it out (though I suspect it's simple). 

@brettc, can you take a look?

R

tests/test_parser.py::test_one FAILED
tests/test_phyml.py::test_simple PASSED
tests/test_phyml.py::test_interleaved PASSED
tests/test_phyml.py::test_subset PASSED
tests/test_raxml.py::test_one PASSED
tests/test_raxml.py::test_parse_nucleotide FAILED
tests/test_raxml.py::test_parse_aminoacid FAILED
tests/test_submodels.py::test_consistency PASSED
tests/test_submodels.py::test_scheme_lengths PASSED
tests/test_subset.py::test_identity PASSED
tests/test_subset.py::test_overlap ERROR
tests/PF2/test_pf2.py::test_missing_sites_warning ERROR
tests/PF2/test_pf2.py::test_overlapping_blocks ERROR

**Comment by roblanf** [comment]
Most of these were me being dumb. The current list now looks like this:

Only three left to fix: test_one, test_parse_nucleotide, and parse_aminoacid

These I still can't figure out.

tests/test_parser.py::test_one FAILED
tests/test_phyml.py::test_simple PASSED
tests/test_phyml.py::test_interleaved PASSED
tests/test_phyml.py::test_subset PASSED
tests/test_raxml.py::test_one PASSED
tests/test_raxml.py::test_parse_nucleotide FAILED
tests/test_raxml.py::test_parse_aminoacid FAILED
tests/test_submodels.py::test_consistency PASSED
tests/test_submodels.py::test_scheme_lengths PASSED
tests/test_subset.py::test_identity PASSED
tests/test_subset.py::test_overlap PASSED
tests/PF2/test_pf2.py::test_missing_sites_warning PASSED
tests/PF2/test_pf2.py::test_overlapping_blocks PASSED

**Comment by brettc** [comment]
Fixed in 9ae670c9c56f13cf295253421df49352f4433b8b
