### ISSUE TITLE
fix full tests with results comparisons

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#51]
The following tests fail, because the new version of phyml or raxml is finding better likelihoods so breaking our rerun tests (either that or updates to the rcluster algorithm are giving slight improvements). In each of these cases I've checked the output, and the differences are very small. Everything else looks good.

For the protein tests that are failing, they fail because I simplified the tests to make them run quicker, so the expected output has changed. 

The fix is to update the results.bin files to runs from the current value. @brettc, can you do this for the following tests:

tests/full_analysis/test_full.py::test_dna[DNA2] FAILED
tests/full_analysis/test_full.py::test_dna[DNA7] FAILED
tests/full_analysis/test_full.py::test_dna[DNA8] FAILED
tests/full_analysis/test_full.py::test_prot[prot1] FAILED
tests/full_analysis/test_full.py::test_prot[prot6] FAILED
tests/full_analysis/test_full.py::test_prot[prot7] FAILED
tests/full_analysis/test_full.py::test_prot[prot8] FAILED

**Comment by brettc** [comment]
Fixed in 957367f6529d2b2487d008b7b63956020333bcb8
