### ISSUE TITLE
update RAxML to very latest version

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#53]
In testing with the 1Kite crew, we have discovered a small bug in the RAxML LG4X model implementation. This is currently being fixed, so before release we have to know that it's fixed, and update our Windows and Mac executables for RAxML. We may need help compiling the windows version, but I have a few people I could ask.

**Comment by pbfrandsen** [comment]
A user had a similar problem on our cluster. He wrote and received an update source code file. However, it also looks like there has been a new release with the fix (https://groups.google.com/forum/#!topic/raxml/2lHCMRKVNac).

**Comment by roblanf** [comment]
As far as I know this is only an issue with the LG4X model. So the other
pragmatic fix is to just remove that from the list of models we use. RIght
now it is included in 'all' and 'allx', so if the problem persists despite
the attempted bug fixes in RAxML, then I'll just take LG4X out of those
lists.

On 7 August 2015 at 03:22, Paul Frandsen <notifications@github.com> wrote:

> A user had a similar problem on our cluster. He wrote and received an
> update source code file. However, it also looks like there has been a new
> release with the fix (
> https://groups.google.com/forum/#!topic/raxml/2lHCMRKVNac).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/53#issuecomment-128449790>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by brettc** [comment]
I'll sort this out. Note that the latest phyml passes all tests, apart from
the ones that compare results, as it appears the BIC etc values have
changed over the versions.

Brett

**Comment by roblanf** [comment]
I've manually updated the mac binary for raxml to 8.2.2, so that I can keep debugging for the 1Kite crew. But we should still aim to have RAxML as a submodule.

**Comment by brettc** [comment]
I just merged the branch with raxml as a submodule. The binary is now one that I built, but it still reports as 8.2.2. I use the SSE version. Note: this breaks some tests, but this is what we need fix for PF2.0.

**Comment by brettc** [comment]
Note: The "right" way to build raxml is now using the submodule included in partitionfinder. I'll make sure this is done before the release (same with phyml). So let's not close this until I've done that.

**Comment by roblanf** [comment]
the latest windows executable for RAxML we can get from here:

few seconds and couldn't really find a path to a previous version of RAxML so...

I downloaded the package available here:
http://sourceforge.net/projects/raxmlgui/
...and in the raxml folder found raxmlHPC_8121.exe (this is version 8.1.21 from May 2015)

This is from a user (Steven) on the google group. Very helpful.

**Comment by roblanf** [comment]
@brettc, what's the status of the submodules? Do they work? I never managed to get them to work.

Are submodules overkill for us here? It's easier to just build static versions of the programs we use, and rely on them... that way we don't have to go crazy if RAxML changes its output format, etc.

**Comment by brettc** [comment]
Having submodules and having static builds are compatible ideas. The idea
being that we know precisely which code (ie. github version of phyml /
raxml) we used to construct our static builds, and can relate them to the
original source code as they are forked from it. A submodule is basically
points to particular version. And that pointer gets version in our source
tree. Also, having submodules doesn't mean we need to update to latest
version of raxml. Quite the opposite, as we fix which version we wish to
use and don't need to change it.

What problems did you have building them? I can look to see what is broken.
They should just point to the forked branches of raxml / phyml in brettc.
Otherwise, where did the static version we currently used come from?

Brett

**Comment by roblanf** [comment]
OK, got it.

Our PhyML version should point to your version of phyml on github.

But our RAxML version should point to the very latest standard-raxml on
github (you could just update your fork I guess)

R

On 1 June 2016 at 17:25, Brett Calcott <notifications@github.com> wrote:

> Having submodules and having static builds are compatible ideas. The idea
> being that we know precisely which code (ie. github version of phyml /
> raxml) we used to construct our static builds, and can relate them to the
> original source code as they are forked from it. A submodule is basically
> points to particular version. And that pointer gets version in our source
> tree. Also, having submodules doesn't mean we need to update to latest
> version of raxml. Quite the opposite, as we fix which version we wish to
> use and don't need to change it.
>
> What problems did you have building them? I can look to see what is broken.
> They should just point to the forked branches of raxml / phyml in brettc.
> Otherwise, where did the static version we currently used come from?
>
> Brett
>
> On Wed, Jun 1, 2016 at 2:10 PM roblanf <notifications@github.com> wrote:
>
> > @brettc <https://github.com/brettc>, what's the status of the
> submodules?
> > Do they work? I never managed to get them to work.
> >
> > Are submodules overkill for us here? It's easier to just build static
> > versions of the programs we use, and rely on them... that way we don't
> have
> > to go crazy if RAxML changes its output format, etc.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/brettc/partitionfinder/issues/53#issuecomment-222874114
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAb6Q9iOjiH3Cp6GEqUk7SYGemXJOthYks5qHOolgaJpZM4FkZS2
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/53#issuecomment-222914072>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2pE40OGhVPBOho_9PUgYCP5lRgCXWAks5qHTQCgaJpZM4FkZS2>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by brettc** [comment]
The idea would be that before a release we would rebuild the programs using the code in the submodules, thus ensuring a consistency for users (they know where the precisly where the code for PF comes from, and where the code for the other tools does too. Thus, consistency, replicability etc etc. 

I’ll look at getting this going, and making it easy for you to do (I thought I had put some scripts there).

Brett

**Comment by roblanf** [comment]
RAxML is updated to the latest version, so I'm closing this. Note that we could still improve our builds a bit, but that's a separate issue. https://github.com/brettc/partitionfinder/commit/0def00d6559cb66f5171ffb25fba70ac04df9e69

**Comment by brettc** [comment]
Can you tell me exactly how you built this? (ie. Which branch, from which
repository, with which options). I take you didn't use the the build script
or the submodule?

**Comment by roblanf** [comment]
Hey Brett,

For mac and Linux, I used this commit from standard-RAxML:

https://github.com/stamatak/standard-RAxML/commit/3abe69bf5339ffe3e1d0abe9f6cc1e8980ab1be7

Then for mac, I built it on my laptop (OSx 10.11.3, using clang) with:

```
make -f Makefile.SSE3.PTHREADS.mac
rm *.o
make -f Makefile.SSE3.mac
rm *.o
```

Then I just rename the pthreads version 'raxml_pthreads', and the
non-pthreads version 'raxml' and drop them in the programs folder.

For Linux, I built it on the server, which uses gcc:

```
make -f Makefile.SSE3.PTHREADS.gcc
rm *.o
make -f Makefile.SSE3.gcc
rm *.o
```

Same deal for renaming, except these are suffixed with '.linux'

For Windows,

I copied and renamed (as above) the relevant .exe files from the folder
'WindowsExecutables_v8.2.7_Alternate/', e.g.
https://github.com/stamatak/standard-RAxML/tree/master/WindowsExecutables_v8.2.7_Alternate

I renamed as above, but left the .exe.

Lemme know if anything's not clear. For now, if we point our submodules to
the commit above, that would probably be useful.

I'll copy-paste these details to the readme in the programs folder, just so
it's clear.

R




On 26 June 2016 at 14:11, Brett Calcott <notifications@github.com> wrote:

> Can you tell me exactly how you built this? (ie. Which branch, from which
> repository, with which options). I take you didn't use the the build script
> or the submodule?
>
>
> On Sun, 26 Jun 2016 at 2:35 PM, roblanf <notifications@github.com> wrote:
>
> > RAxML is updated to the latest version, so I'm closing this. Note that we
> > could still improve our builds a bit, but that's a separate issue.
> 0def00d
> > <
> https://github.com/brettc/partitionfinder/commit/0def00d6559cb66f5171ffb25fba70ac04df9e69
> >
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/brettc/partitionfinder/issues/53#issuecomment-228580939
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAb6Q1hxWZT2Ua-NIKZHfKyPB7I99ASdks5qPeVugaJpZM4FkZS2
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/53#issuecomment-228583342>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2pE_CzpZclq1wVAUNSxCjSRMn4hv5Lks5qPfvrgaJpZM4FkZS2>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com
