### ISSUE TITLE
add section to manual on major differences with PF1

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#54]
pretty self explanatory, but if anyone thinks of anything we should add (this list will also be useful for the paper), then stick it here.

* model lists are a bit different
* there are a lot more models implemented
* kmeans algorithm is implemented
* but it uses entropy, not TIGER rates, which is quicker (O(N) with sites, rather than O(N-squared)) and usually better
* rcluster is now controlled with --rcluster-max not --rcluster-percent. This makes it O(N) with the number of data blocks, rather than O(N-squared). I need to do a few comparisons with the default settings to measure the difference this makes.
* much less file writing (great for speed, disk space, and use on clusters with I/O limits)
* best_schemes.txt contains a lot more information
* we use Numpy, Scipy, and scikit-learn, so everything is quicker
* installing the right version of Python (with all the dependencies) is now much easier with Anaconda point-and-click installers (especially for Windows users)
* parallelisation is much more efficient (i.e. we analyse multiple models from multiple subsets at once, which means that we can make much better use of all the available processors)

**Comment by cmayer** [comment]
Hi Rob,

Anaconda also makes it much simpler to obtain a working environment on Linux clusters. It works out of the box with user privileges. It cannot be simpler to use.

Best 
Christoph


Christoph Mayer
Forschungsmuseum Alexander Koenig Bonn 
Email c.mayer.zfmk@uni-bonn.de
Tel.: 0228 9122403

**Comment by roblanf** [comment]
NB rcluster is now controlled with rcluster-max and rcluster-percent. Updated in the manual.

**Comment by pbfrandsen** [comment]
Since we pointed to the 'paul_develop' version of the kmeans stuff with our paper, it also might worth pointing out the other improvements made to kmeans. You noted one (using site entropies instead of site rates). There are at least two other big ones:
1. Works with RAxML
2. Works with protein alignments

**Comment by roblanf** [comment]
Here are a couple of other things that come to mind:

1. I just completely rewrote the greedy algorithm in PF2. It now uses a lot of the same machinery as the relaxed clustering algorithm, which saves a lot of unnecessary computation by tracking differences in AICc (or whatever) scores in a big matrix as the algorithm proceeds. 

2. The kmeans algorithm now has two extra options (the latter hasn't been pushed yet, but I'll do it soon):
2.1. --min-subset-size, let's users set the minimum allowable size of a subset that kmeans will spit out. This is done with downstream applications (like bootstrapping) in mind. But it's also biologically motivated insofar as even if the AICc score improves when you split of a 1bp subset, I don't think that's a good biological move. The default is 100 for now. But we can change that. The 'old' kmeans algorithm effectively has this set to 1. 
 
2.2. --all-states, is a setting that restricts kmeans to considering only subsets in which all states (e.g. ACTG for DNA) are present. This again is done with downstream applications in mind. The default is off, but you can set it at the commandline by just adding the flag. @pbfrandsen, one thing you could ask the 1Kite folks is what they want to do about missing data here. Right now, I consider that a gap or missing data ('-' or '?') is equivalent to having all states present (both for protein and DNA). I can change this, but I don't actually know what RAxML or ExaML do, so I didn't know off hand how to set it appropriately for those programs. My best guess is that treating a gap as all states is the most sensible thing, since likelihood algorithms sum over all states when there's missing data. This option also deals with ambiguous bases fine.

**Comment by cmayer** [comment]
Hi Rob,

very nice.

Concerning the --all-states:
A gap is the same as an X. This is perfectly reasonable.

But an X is not as good as having all states to be present. I would prefer that X and N are ignored in the all states count.
If there are only X or N in one column, Raxml removes this column. Since Raxml counts residues before it starts, I do not think that X or N should count as anything, since I
do not think Alexi would count an X or N as a representative for all states. But if raxml enforces all states to be truly present, your convention would not help much to avoid
downstream problems.

Best
Christoph



Am 15.09.2015 um 01:32 schrieb roblanf:

> Here are a couple of other things that come to mind:
> 
> I just completely rewrote the greedy algorithm in PF2. It now uses a lot of the same machinery as the relaxed clustering algorithm, which saves a lot of unnecessary computation by tracking differences in AICc (or whatever) scores in a big matrix as the algorithm proceeds.
> 
> The kmeans algorithm now has two extra options (the latter hasn't been pushed yet, but I'll do it soon):
> 2.1. --min-subset-size, let's users set the minimum allowable size of a subset that kmeans will spit out. This is done with downstream applications (like bootstrapping) in mind. But it's also biologically motivated insofar as even if the AICc score improves when you split of a 1bp subset, I don't think that's a good biological move. The default is 100 for now. But we can change that. The 'old' kmeans algorithm effectively has this set to 1.
> 
> 2.2. --all-states, is a setting that restricts kmeans to considering only subsets in which all states (e.g. ACTG for DNA) are present. This again is done with downstream applications in mind. The default is off, but you can set it at the commandline by just adding the flag. @pbfrandsen, one thing you could ask the 1Kite folks is what they want to do about missing data here. Right now, I consider that a gap or missing data ('-' or '?') is equivalent to having all states present (both for protein and DNA). I can change this, but I don't actually know what RAxML or ExaML do, so I didn't know off hand how to set it appropriately for those programs. My best guess is that treating a gap as all states is the most sensible thing, since likelihood algorithms sum over all states when there's missing data. This option also deals with ambiguous bases fine.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
Hi Christoph,

Happy to implement this. Can you test exactly what RAxML does and let me
know. This should be fairly simple to do by trying a few runs with a
limited number of amino acids, then adding in X's, -'s, and ?'s in turn and
just writing down the behaviour of RAxML and ExaML.

Once we have that figured out, I can configure the --all-states option
appropriately.

R

On 15 September 2015 at 09:53, cmayer <notifications@github.com> wrote:

> Hi Rob,
>
> very nice.
>
> Concerning the --all-states:
> A gap is the same as an X. This is perfectly reasonable.
>
> But an X is not as good as having all states to be present. I would prefer
> that X and N are ignored in the all states count.
> If there are only X or N in one column, Raxml removes this column. Since
> Raxml counts residues before it starts, I do not think that X or N should
> count as anything, since I
> do not think Alexi would count an X or N as a representative for all
> states. But if raxml enforces all states to be truly present, your
> convention would not help much to avoid
> downstream problems.
>
> Best
> Christoph
>
>
>
> Am 15.09.2015 um 01:32 schrieb roblanf:
>
> > Here are a couple of other things that come to mind:
> >
> > I just completely rewrote the greedy algorithm in PF2. It now uses a lot
> of the same machinery as the relaxed clustering algorithm, which saves a
> lot of unnecessary computation by tracking differences in AICc (or
> whatever) scores in a big matrix as the algorithm proceeds.
> >
> > The kmeans algorithm now has two extra options (the latter hasn't been
> pushed yet, but I'll do it soon):
> > 2.1. --min-subset-size, let's users set the minimum allowable size of a
> subset that kmeans will spit out. This is done with downstream applications
> (like bootstrapping) in mind. But it's also biologically motivated insofar
> as even if the AICc score improves when you split of a 1bp subset, I don't
> think that's a good biological move. The default is 100 for now. But we can
> change that. The 'old' kmeans algorithm effectively has this set to 1.
> >
> > 2.2. --all-states, is a setting that restricts kmeans to considering
> only subsets in which all states (e.g. ACTG for DNA) are present. This
> again is done with downstream applications in mind. The default is off, but
> you can set it at the commandline by just adding the flag. @pbfrandsen, one
> thing you could ask the 1Kite folks is what they want to do about missing
> data here. Right now, I consider that a gap or missing data ('-' or '?') is
> equivalent to having all states present (both for protein and DNA). I can
> change this, but I don't actually know what RAxML or ExaML do, so I didn't
> know off hand how to set it appropriately for those programs. My best guess
> is that treating a gap as all states is the most sensible thing, since
> likelihood algorithms sum over all states when there's missing data. This
> option also deals with ambiguous bases fine.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> ****************************************
> Dr. Christoph Mayer
> Email: c.mayer.zfmk@uni-bonn.de
> Tel.: +49 (0)228 9122 403
>
> Zoologisches Forschungsmuseum Alexander Koenig
> - Leibniz Institut für Biodiversität der Tiere -
> Adenauerallee 160
> 53113 Bonn, Germany
> www.zfmk.de
>
> Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
> Sitz: Bonn
> ****************************************
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/54#issuecomment-140235586>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
To clarify the previous point...

I want this flag to be generally useful as well as specifically useful to the 1Kite project. So, while I appreciate that RAxML and (presumably) ExaML will not analyse a dataset with a column of X's, ?'s, or -'s (or some combination), I do think that those kind of columns are something that can (perhaps should) be dealt with by the user before analysing their data. I don't see (correct me if I'm wrong) why anyone would want to even try and analyse a dataset that had an entire column of X's, ?'s, and -'s. 

On the other hand, I can of course see why some folks might have columns where only a small number of species had data, and other rows for those columns were ?'s, X's, and -'s. So, the uncertainty I'd like cleared up is how RAxML treats those columns. E.g., will it analyse a dataset in which a partition has only one species with data, and the rest are gaps? What about 2 or 3 species with data?

Does that make sense?

**Comment by roblanf** [comment]
Here's another one for PF2:

@brettc completely rewrote how we parse alignments. We can now load a 12million bp alignment in 20s on a laptop.

**Comment by cmayer** [comment]
Hi Rob,

I tested this. It is as I expected it.
I gave it only 14 states and raxml tells me:

Partition No Name Provided number 0 has a problem, the number of expected states is 20 the number of states that are present is 14.
Please go and fix your data!

I get this irrespective of whether I replace one of the AAs by an X or not.

Interestingly for my test data set this is only a warning and the tree reconstruction proceeds and produces a meaningless tree
due to the small amount of data. I know from other people that raxml sometimes completely refused to proceed after this message.

The problem with Examl or better its data coverter is that it is not very good a given you a reason if it does not do anything.

Best
Christoph


Am 15.09.2015 um 03:17 schrieb roblanf:

> Hi Christoph,
> 
> Happy to implement this. Can you test exactly what RAxML does and let me
> know. This should be fairly simple to do by trying a few runs with a
> limited number of amino acids, then adding in X's, -'s, and ?'s in turn and
> just writing down the behaviour of RAxML and ExaML.
> 
> Once we have that figured out, I can configure the --all-states option
> appropriately.
> 
> R
> 
> On 15 September 2015 at 09:53, cmayer <notifications@github.com> wrote:
> 
> > Hi Rob,
> >
> > very nice.
> >
> > Concerning the --all-states:
> > A gap is the same as an X. This is perfectly reasonable.
> >
> > But an X is not as good as having all states to be present. I would prefer
> > that X and N are ignored in the all states count.
> > If there are only X or N in one column, Raxml removes this column. Since
> > Raxml counts residues before it starts, I do not think that X or N should
> > count as anything, since I
> > do not think Alexi would count an X or N as a representative for all
> > states. But if raxml enforces all states to be truly present, your
> > convention would not help much to avoid
> > downstream problems.
> >
> > Best
> > Christoph
> >
> >
> >
> > Am 15.09.2015 um 01:32 schrieb roblanf:
> >
> > > Here are a couple of other things that come to mind:
> > >
> > > I just completely rewrote the greedy algorithm in PF2. It now uses a lot
> > of the same machinery as the relaxed clustering algorithm, which saves a
> > lot of unnecessary computation by tracking differences in AICc (or
> > whatever) scores in a big matrix as the algorithm proceeds.
> > >
> > > The kmeans algorithm now has two extra options (the latter hasn't been
> > pushed yet, but I'll do it soon):
> > > 2.1. --min-subset-size, let's users set the minimum allowable size of a
> > subset that kmeans will spit out. This is done with downstream applications
> > (like bootstrapping) in mind. But it's also biologically motivated insofar
> > as even if the AICc score improves when you split of a 1bp subset, I don't
> > think that's a good biological move. The default is 100 for now. But we can
> > change that. The 'old' kmeans algorithm effectively has this set to 1.
> > >
> > > 2.2. --all-states, is a setting that restricts kmeans to considering
> > only subsets in which all states (e.g. ACTG for DNA) are present. This
> > again is done with downstream applications in mind. The default is off, but
> > you can set it at the commandline by just adding the flag. @pbfrandsen, one
> > thing you could ask the 1Kite folks is what they want to do about missing
> > data here. Right now, I consider that a gap or missing data ('-' or '?') is
> > equivalent to having all states present (both for protein and DNA). I can
> > change this, but I don't actually know what RAxML or ExaML do, so I didn't
> > know off hand how to set it appropriately for those programs. My best guess
> > is that treating a gap as all states is the most sensible thing, since
> > likelihood algorithms sum over all states when there's missing data. This
> > option also deals with ambiguous bases fine.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > ****************************************
> > Dr. Christoph Mayer
> > Email: c.mayer.zfmk@uni-bonn.de
> > Tel.: +49 (0)228 9122 403
> >
> > Zoologisches Forschungsmuseum Alexander Koenig
> > - Leibniz Institut für Biodiversität der Tiere -
> > Adenauerallee 160
> > 53113 Bonn, Germany
> > www.zfmk.de
> >
> > Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
> > Sitz: Bonn
> > ****************************************
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/brettc/partitionfinder/issues/54#issuecomment-140235586>
> > .
> >
> 
> 
> 
> -- 
> Rob Lanfear
> School of Biological Sciences,
> Macquarie University,
> Sydney
> 
> phone: +61 (0)2 9850 8204
> 
> www.robertlanfear.com
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
OK, so we want 'definite' presence of all 20 amino acids in that case. In which case I guess I should score 'X', '-', and '?' as having no data. 

Do you have a dataset you can use to test this flag? I.e. a dataset which when you run kmeans normally you get issues with RAxML to do with missing states. That would be the best way to know if we have exactly what we need with this setting.

**Comment by roblanf** [comment]
* output mrbayes block that describes partitioning scheme for DNA and amino acid alignment
* output nexus block for the same

**Comment by roblanf** [comment]
done to the extent that it's required.
