### ISSUE TITLE
Manually check lastest phyml

### ISSUE THREAD

**Issue by brettc** [brettc/partitionfinder#56]
The latest phyml generates some different information scores. Spot check the results using --save-phylofiles, and just double check that we are extracting the likelihoods correctly, and that the models we're specifying are the models we're getting.

**Comment by roblanf** [comment]
Yo @brettc, is this on the develop branch?

**Comment by brettc** [comment]
Yep. I fixed all of test failures, but you still might want to spot check phylofiles.

**Comment by roblanf** [comment]
Done. I manually checked about 20 files from 20 different subsets. In each case we get the lnL scores correctly. 

Also checked about 15 of the models, and they were all correct. So, looks good to me.
