### ISSUE TITLE
fix tiger_DNA import in kmeans

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#57]
Right now we try and import from _tiger. Most folks won't have this, and it's not a user facing option anyway. 

So, the fix is to change the import at the top of kmeans.py to look something more like this:

try: 
    from _tiger import TigerDNA
except:
    if user asked for tiger or tigger rates:
        raise error ("you need to install tiger or tigger, this is an unsupported option and you're on your own here. Good luck. blah blah")
    else:
        pass

**Comment by pbfrandsen** [comment]
Ahh. Duh. I'll take care of this.

sent from my mobile phone, apologies for any typos

**Comment by pbfrandsen** [comment]
@brettc is the global config still supposed to work? I added this block, but I get an error that the Configure object has no attribute 'kmeans' (which it clearly should when looking at the config module).
```
try:
    from _tiger import TigerDNA
except:
    if the_config.kmeans == 'tiger':
        raise PhylogenyProgramError("You have selected kmeans and tiger \
            rates. This is an unsupported option, if you still wish to use \
            this option, you must compile the tiger code.")
    else:
        pass
```

**Comment by roblanf** [comment]
fixed in https://github.com/brettc/partitionfinder/commit/a818b87fee88868070ddb9bfb47bf3adf5034dfc
