### ISSUE TITLE
Update minimum versions for python (and anaconda?) in Manual

### ISSUE THREAD

**Issue by brettc** [brettc/partitionfinder#64]
Useful reminders from Christoph:

one of the readme says that python version 2.7 is needed
and the manual says 2.7.x.

Some time age we already had problems with python versions before 2.7.3.
They had a bug in the mulithreading and caused unexpected crashes.
You remember. We had a long email conversation about this.
We concluded that one of the bug fixes in 2.7.3 was the likely reason for these crashes,
and indeed 2.7.3 worked fine.

Anaconda (1.8.0) which I was using had python 2.7.5 with some old libraries. This version did not work here.
Anaconda (2.3.0) brings python 2.7.10 and works.

I think this information could be updated in the manual.
Of course it is not clear whether the python version 2.7.10 is required or whether,
2.7.5 (if it works) together with more recent libraries is fine as well.

Anyway. I think 2.7.3 is required for sure and anaconda has to be sufficiently recent as well.

**Comment by roblanf** [comment]
Done. Recommendations are now to use Python 2.7.10 or higher (but not 3.x obvs), and Anaconda 2.3.0 or higher.
