### ISSUE TITLE
loading big alignments

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#65]
a couple of folks on the google group have noted that on linux clusters loading huge alignments is an issue. 

I can't recreate the issue on my mac, so we don't yet know exactly what's going on.

However, our alignment parsing is currently pretty clunky - we read in the whole thing and then parse it. We can do better by streaming it. 

E.g. 

We know that line 1 is always the header.
Each subsequent line is a (species, sequence) tuple.

At the very least we could stream the alignment line by line and convert to np.array() on the fly. That should be more memory efficient, and maybe (?) solve this mysterious issue.

**Comment by cmayer** [comment]
Hi Rob,

no issues here. But what is huge? My tests might not be huge enough.
I have one test analysis running on my Ubuntu machine.

Best
Christoph


Am 20.08.2015 um 03:16 schrieb roblanf:

> a couple of folks on the google group have noted that on linux clusters loading huge alignments is an issue.
> 
> I can't recreate the issue on my mac, so we don't yet know exactly what's going on.
> 
> However, our alignment parsing is currently pretty clunky - we read in the whole thing and then parse it. We can do better by streaming it.
> 
> E.g.
> 
> We know that line 1 is always the header.
> Each subsequent line is a (species, sequence) tuple.
> 
> At the very least we could stream the alignment line by line and convert to np.array() on the fly. That should be more memory efficient, and maybe (?) solve this mysterious issue.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
Hi Christoph,

The kind of analyses folks are talking about are typically ~3 million base pairs. I made one of these datasets by just concatenating the 1Kite dataset (https://github.com/roblanf/PartitionedAlignments/tree/master/datasets/Misof_2014) 4 times. On my desktop mac, I can load the entire alignment with ~1.5GB memory, regardless of the version of PF that I use. 

There are a few more details on the thread in the google group here: https://groups.google.com/forum/#!topic/partitionfinder/ZsGd-t7FRf4

But if you wanted to try something like that out, I'd be grateful for any feedback on performance on your machine.

Rob

**Comment by roblanf** [comment]
Update. The alignments causing problems are 12 million base pairs and 15 species. It looks like it's an issue with Python's string reading, which we use at the moment. There are probably ways around it...

**Comment by brettc** [comment]
Fixed in ec02dd30071f71bbfda8078fcf99340732513f14
