### ISSUE TITLE
Outstanding TODO list items (from removed TODO.txt)

### ISSUE THREAD

**Issue by brettc** [brettc/partitionfinder#67]
* right now we allow data blocks to have identical names. This is not a good idea. Fix.

* odd bug - we seem to have lost the ability to tell whether an analysis was run in phyml or raxml
  so we run the risk of taking results from shitty subsets. Need to add this to the old config
  comparison method. 

* Add in sensible dependency checks at the start, and print out useful error messages.
    e.g. "You need to have SciKit-Learn installed to run this analysis, to do that, 
    please install the anaconda python distribution from here..."

Brett test enhancing:
---------------------

TODO 
* change name back to full_name in subset reporting
* Only makes sense to report ONE IC in the greedy algo output...
* make progress part of the reporter too
* change name back to full_name in subset reporting
* think about using __slots__ in subset and scheme?
* Consider dropping part_subsets in schemes (only need it for checking...)
* think about ditching schemes as we go, and subset info?

**Comment by roblanf** [comment]
removed stuff we have already done...

**Comment by roblanf** [comment]
all of these are done.
