### ISSUE TITLE
Enable valid character checking in the alignment parser?

### ISSUE THREAD

**Issue by brettc** [brettc/partitionfinder#71]
I have some code in the new alignment parser to check valid characters using these definitions:
```
valid_nucleotide = "AGCTUMRWSYKBDHVNX.-?"
valid_amino = "ARNBDCQZEGHILKMFPSTWYVX.-?"
```

I want someone to tell me that checking these characters is the right thing to do (I don't want to spit errors out which aren't going to matter to the downstream apps raxml and phyml...). Note that this validation is currently NOT enabled.

**Comment by roblanf** [comment]
You shouldn't validate when you read in the whole alignment. Here's why. 

We currently allow folks to have mixed-state alignments, and just specify parts of them in the data-blocks. E.g. you could have an alignment with some DNA and some amino acid columns. As long as you specify in the datablocks a set of columns that applies to just one or the other state, PF should run OK.

But other than that, I think this should be OK. I.e. if you run this check only on the filtered alignments that we use. 

If that's hard, I'd leave it out for now. I am not uncomfortable with putting this in the users' hands.

**Comment by brettc** [comment]
I'm going to just not do this for now.
