### ISSUE TITLE
PF2 pre-release 11 is looking for the wrong tree file following estimation of RAxML tree

### ISSUE THREAD

**Issue by marekborowiec** [brettc/partitionfinder#85]
After setting up an analysis with the `--ml-tree` option I get this error:

```
ERROR    | 2016-01-30 02:44:43,993 | A program that Partitionfinder uses failed. Output follows, in case it's helpful for finding the problem
ERROR    | 2016-01-30 02:44:43,993 | 
ERROR    | 2016-01-30 02:44:43,994 | . command-line: /datadrive/partitionfinder-2.0.0-pre11/programs/phyml --run_id GTR+I+G -b 0 -i ./analysis/phylofiles/58ab28da375c2cc3efefce8d102a994b.phy -u ./analysis/start_tree/filtered_source.phy_phyml_tree -o lr -m 012345 -f e -v e -a e -c 4 --min_diff_lk_local 0.01 --min_diff_lk_global 0.01 --no_memory_check . The file './analysis/start_tree/filtered_source.phy_phyml_tree' doesn't exist. . Type any key to exit.
```

It looks like the tree PF2 should be looking for is `./analysis/start_tree/RAxML_result.BLTREE`.
When I move this RAxML tree to the input folder and re-run the program with it as user-supplied topology it works fine.

**Comment by roblanf** [comment]
Hi Marek,

Sorry for the slow reply - I've been on paternity leave.

Can you tell me the commandline you are using to run this analysis. My guess from the output is that you did not specify the --raxml flag, is that right? I need to add in a condition for what the program should do when you want to use the --ml-tree option in this case.

Rob

**Comment by marekborowiec** [comment]
Correct, I haven't used `--raxml`. I figured out later that using `--raxml` in combination with `--ml-tree` works. This is a minor bug, but, like you say, a condition would be nice to make sure that the program doesn't trip following estimation of ML tree.

Best,
Marek

**Comment by marekborowiec** [comment]
I'm now working with pre-release 13 and still have a similar problem, although now there is no error. I want to look for MrBayes models using the greedy algorithm and so cannot use the `--raxml` which limits models to variations of `GTR`. I run PF with:
```
python ~/Phylo-software/partitionfinder-2.0.0-pre13/PartitionFinder.py --ml-tree -p 8 .
```
This estimates the ML tree fine, then hangs when starting phyml analyses. In debug mode, I can see that the RAxML tree is correctly estimated ant saved into `./analysis/start_tree/RAxML_result.BLTREE`. However, a few lines below PF declares:
```
starting tree with branch lengths is here: ./analysis/start_tree/filtered_source.phy_phyml_tree.txt
```
In the end, PF starts eight phyml runs trying to use that tree and hangs. After I rename (or copy) the 
RAxML result tree to `filtered_source.phy_phyml_tree.txt` and restart the analysis, everything runs smoothly.

**Comment by roblanf** [comment]
Hi Marek,

Thanks for this, I'll take a look as soon as I can.

Rob

On 23 April 2016 at 08:34, Marek <notifications@github.com> wrote:

> I'm now working with pre-release 13 and still have a similar problem,
> although now there is no error. I want to look for MrBayes models using the
> greedy algorithm and so cannot use the --raxml which limits models to
> variations of GTR. I run PF with:
>
> python ~/Phylo-software/partitionfinder-2.0.0-pre13/PartitionFinder.py --ml-tree -p 8 .
>
> This estimates the ML tree fine, then hangs when starting phyml analyses.
> In debug mode, I can see that the RAxML tree is correctly estimated ant
> saved into ./analysis/start_tree/RAxML_result.BLTREE. However, a few
> lines below PF declares:
>
> starting tree with branch lengths is here: ./analysis/start_tree/filtered_source.phy_phyml_tree.txt
>
> In the end, PF starts eight phyml runs trying to use that tree and hangs.
> After I rename (or copy) the
> RAxML result tree to filtered_source.phy_phyml_tree.txt and restart the
> analysis, everything runs smoothly.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/85#issuecomment-213612996>
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
Done (sorry it took a long time!): https://github.com/brettc/partitionfinder/commit/f6dd6eca5da4fdb080ae17ddb7c2a46feecebb74
