### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by kdmurray91** [brettc/partitionfinder#87]
Hi Brett,

I'm packaging partitionfinder for Debian (and thus derivatives like Ubuntu) as part of the [Debian Med](https://www.debian.org/devel/debian-med/) team. One thing blocking this is that many files (e.g. most tests) do not have copyright headers or any license information. I understand that the partition finder code base is GPL licensed, but the Debian bureaucracy prefers that files have some minimal authorship information in a header, or at least a LICENSE (or COPYING or similar) file in the root of the repository.

I believe it will be OK for now if you state here that all unlabeled source files are copyright yourself (and any other authors), and licensed under the GPL. If this is not the case, please add headers as appropriate ASAP so this package can be added to Debian.

Cheers,
Kevin

**Comment by brettc** [comment]
Hi Kevin,

I prefer to to put a LICENSE file in the root. Are you packaging 1.x or the the latest *nearly* released 2.x version?

Brett

**Comment by wookietreiber** [comment]
👍 on adding a LICENSE file. This is a rather recommended thing to do.
