### ISSUE TITLE
finding anaconda python

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#89]
A couple of users have reported odd behaviour when they have old Python versions installed, because invoking 'python' uses the old version not the anaconda version. Since this issue seems rare, rather than changing the manual or the default instructions, I think it's better if we do this:

1. Code a test to see if we're running the anaconda python (if we can't do that, then try/except loading all the dependencies)
2. If step 1 fails, print an error, with a help message to try explicitly pointing to the anaconda Python version. I.e. instead of starting the command with 'python' you would do 

windows

'''
C:\Anaconda\Python.exe
'''

mac

'''
/Users/username/anaconda/bin/python
'''

Thoughts @brettc @pbfrandsen ?

**Comment by brettc** [comment]
Not sure coding anything is the best option. Some users might be happy NOT
using anaconda.

A section in the manual might be better. Note that :

> which python

tells you which python you are using in mac / linux.

I believe that on most Windows systems:

> where.exe python

Will tell you what python will be invoked too…

see here:
http://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line

**Comment by cmayer** [comment]
Hi Rob,

my preferred approach is to use the full path to the python binary.
This allows me to have multiple pythons.
In particular in clusters I find that this is the most convenient way.

Best
Christoph


Am 18.02.2016 um 23:33 schrieb roblanf <notifications@github.com>:

> A couple of users have reported odd behaviour when they have old Python versions installed, because invoking 'python' uses the old version not the anaconda version. Since this issue seems rare, rather than changing the manual or the default instructions, I think it's better if we do this:
> 
> Code a test to see if we're running the anaconda python (if we can't do that, then try/except loading all the dependencies)
> If step 1 fails, print an error, with a help message to try explicitly pointing to the anaconda Python version. I.e. instead of starting the command with 'python' you would do
> windows
> 
> '''
> C:\Anaconda\Python.exe
> '''
> 
> mac
> 
> '''
> /Users/username/anaconda/bin/python
> '''
> 
> Thoughts @brettc @pbfrandsen ?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

****************************************
Dr. Christoph Mayer
Email:  c.mayer.zfmk@uni-bonn.de
Tel.:   +49 (0)228 9122 403

Zoologisches Forschungsmuseum Alexander Koenig
- Leibniz Institut für Biodiversität der Tiere -
Adenauerallee 160
53113 Bonn, Germany 
www.zfmk.de

Stiftung des öffentlichen Rechts; Direktor: Prof. J. W. Wägele
Sitz: Bonn
****************************************

**Comment by roblanf** [comment]
Hi All, 

Thanks for the feedback. The main thing in my opinion is that we provide clear instructions to naive users. 

So @brettc, what if we code an explicit test for all dependencies, and if any are missing we spit a helpful error message with a step-by-step guide. E.g. 

1. Check which python version you are using with ```which python```

2. If you were expecting to be using the anaconda python version, but ```which python``` doesn't say that you are, you need to point to it explicitly, and here's how...

The key here is to build something which means that users don't have to post on the forum (or even look for the forum) to figure out the answer. If the answer is contained in the error message, I think that's the best option. It also keeps the manual simple, since it seems that most of the time the anaconda install makes itself the default python install anyway. And I prefer not to expand the manual to include things about how to point to specific python installs, or to alter your PATH, or whatever (though maybe we should).

I guess my main response to @brettc is that instead of putting this in the manual (where I doubt most folks will actually look) it might be better to put it in an error message that people will get precisely when they need it. In fact, we can just put it in both places, no?

R

**Comment by brettc** [comment]
Ok - I think that sounds do-able. And you are right, immediate feedback
would be better.

We can check for ImportError’s in python, and then maybe do some analysis.
Python has a bunch of libraries that tell you about where it is located,
and what version it is.

Perhaps we could create a separate program that did this. ie.
“check_setup.py”…

Brett

**Comment by pbfrandsen** [comment]
This sounds reasonable to me. Anaconda generally just automatically adds
its location to the PATH in the .bashrc when it's installed (in the case of
Mac and Linux users, I have no idea what the analog is on Windows
machines). I think you can choose not to do this during the install and
some people may do this accidentally. Would it be overkill to include a
statement about how to check your path/add something to your path if "which
python" doesn't yield the anticipated result?

Paul

sent from my mobile phone, apologies for any typos

**Comment by roblanf** [comment]
I think that's a good idea Paul. Maybe after the anaconda install
instructions in the manual, we can have a section about 'which python' and
what to do if the result isn't the anaconda python you just installed.

I guess there are two options:

1) Put the anaconda Python first in your PATH (and whatever it is you do on
windows)
2) Call anaconda Python specifically every time you run PartitionFinder

As long as we can provide clear instructions to Windows/Mac/Linux users
this should be fine I think.

R

On 19 February 2016 at 12:52, Paul Frandsen <notifications@github.com>
wrote:

> This sounds reasonable to me. Anaconda generally just automatically adds
> its location to the PATH in the .bashrc when it's installed (in the case of
> Mac and Linux users, I have no idea what the analog is on Windows
> machines). I think you can choose not to do this during the install and
> some people may do this accidentally. Would it be overkill to include a
> statement about how to check your path/add something to your path if "which
> python" doesn't yield the anticipated result?
>
> Paul
>
> sent from my mobile phone, apologies for any typos
>
> On Feb 18, 2016 6:26 PM, "Brett Calcott" <notifications@github.com> wrote:
>
> > Ok - I think that sounds do-able. And you are right, immediate feedback
> > would be better.
> >
> > We can check for ImportError’s in python, and then maybe do some
> analysis.
> > Python has a bunch of libraries that tell you about where it is located,
> > and what version it is.
> >
> > Perhaps we could create a separate program that did this. ie.
> > “check_setup.py”…
> >
> > Brett
> >
> > On Fri, Feb 19, 2016 at 11:51 AM, roblanf <notifications@github.com>
> > wrote:
> >
> > > Hi All,
> > >
> > > Thanks for the feedback. The main thing in my opinion is that we
> provide
> > > clear instructions to naive users.
> > >
> > > So @brettc <https://github.com/brettc>, what if we code an explicit
> test
> > > for all dependencies, and if any are missing we spit a helpful error
> > > message with a step-by-step guide. E.g.
> > >
> > > 1.
> > >
> > > Check which python version you are using with which python
> > > 2.
> > >
> > > If you were expecting to be using the anaconda python version, but
> which
> > > python doesn't say that you are, you need to point to it explicitly,
> > > and here's how...
> > >
> > > The key here is to build something which means that users don't have to
> > > post on the forum (or even look for the forum) to figure out the
> answer.
> > If
> > > the answer is contained in the error message, I think that's the best
> > > option. It also keeps the manual simple, since it seems that most of
> the
> > > time the anaconda install makes itself the default python install
> anyway.
> > > And I prefer not to expand the manual to include things about how to
> > point
> > > to specific python installs, or to alter your PATH, or whatever (though
> > > maybe we should).
> > >
> > > I guess my main response to @brettc <https://github.com/brettc> is
> that
> > > instead of putting this in the manual (where I doubt most folks will
> > > actually look) it might be better to put it in an error message that
> > people
> > > will get precisely when they need it. In fact, we can just put it in
> both
> > > places, no?
> > >
> > > R
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/brettc/partitionfinder/issues/89#issuecomment-185968420
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/brettc/partitionfinder/issues/89#issuecomment-185978588
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettc/partitionfinder/issues/89#issuecomment-186009383>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
On re-reading this, I think it's overkill. Let's just see what happens when we release PF2. The forum is there if folks are having trouble, and if lots of folks are having the same problem, we can code something along these lines for PF2.0.1. 

Closing for now.
