### ISSUE TITLE
check morphology models

### ISSUE THREAD

**Issue by roblanf** [brettc/partitionfinder#96]
The job here is to look carefully at the last four lines of the models.csv file on the feature/morph2 branch. 

What I need to know is: 

1. Are these the correct four models to implement?
2. Should there be more models implemented?
3. Are the number of parameters for each model correct? 
4. Are the RAxML commandlines correct for these models?

**Comment by roblanf** [comment]
@wrightaprilm, could you take this one on. This is hopefully not a huge amount of work, but you're by far the best placed to do it. Let me know.

**Comment by roblanf** [comment]
Hey @wrightaprilm, can you tell me how many paramters each of the morphology models should have? 

Specifically, for these four models:

```
BINARY+G
BINARY+G+A
MULTISTATE+G
MULTISTATE+G+A
```

How many *free* parameters do they have in each of these categories:

```
Rate matrix
Base (??? for morph???) frequencies
Rate variation
```

**Comment by wrightaprilm** [comment]
Ooops, missed this. 

There's only one parameter in the base Mk model (base frequencies assumed equal) - transition rate. Since transition rate is assumed to be equal, it's not a free parameter. So I think the number is zero. I am actually not sure how +G gets treated by RAxML.

**Comment by roblanf** [comment]
done.
